version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "userpassword"
      POSTGRES_DB: "dbname"
      TZ: "America/Fortaleza"